cmsopendata/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from cmsopendata import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cmsopendata.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('openaccess.urls', namespace="openaccess")),
)

openaccess/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from openaccess import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cmsopendata.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^TermsofUse$',
        TemplateView.as_view(template_name="openaccess/termsofuse.html"),
        name='termsofuse'),
    url(r'^PrivacyPolicy$',
        TemplateView.as_view(template_name="openaccess/privacypolicy.html"),
        name='privacypolicy'),
    url(r'^Contact$', 
        TemplateView.as_view(template_name="openaccess/contact.html"),
        name='contact'),
    url(r'^Analysis$', views.AnalysisView.as_view(), name='analysis'),
    url(r'^ssh-access$', views.SSHView.as_view(), name='ssh'),
)

openaccess/models.py
import os
import stat
from Crypto.PublicKey import RSA

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

import paramiko

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    key = models.TextField()
    username = models.CharField(max_length=20)
    extra_keys = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.username

    def setup_user(self):
        self.username = 'cms%04d' % self.user.pk
        self._generate_key()
        self._create_remote_user()
        self._save_profile_key()

    def _save_profile_key(self):
        profile_dir = os.path.join(settings.OPENACCESS_GATEONE_PROFILE_DIR,
                                   self.username, '.ssh')
        # TODO: do this properly
        if not os.path.exists(profile_dir):
            os.makedirs(profile_dir)
        key_file = os.path.join(profile_dir, 'id_rsa')
        with open(key_file, 'w+') as f:
            f.write(self.key) 
        os.chmod(key_file, stat.S_IREAD | stat.S_IWRITE)
        pub_key_file = os.path.join(profile_dir, 'id_rsa.pub')
        with open(pub_key_file, 'w+') as f:
            f.write(self.get_public_key()) 
        os.chmod(key_file, stat.S_IREAD | stat.S_IWRITE)
        defaults_file = os.path.join(profile_dir, '.default_ids')
        with open(defaults_file, 'w+') as f:
            f.write("id_rsa\n") 
        os.chmod(key_file, stat.S_IREAD | stat.S_IWRITE)
 
    def _generate_key(self):
        rsa_key = RSA.generate(2048, os.urandom)
        self.key = rsa_key.exportKey()

    def get_public_key(self):
        key = RSA.importKey(self.key) 
        return key.exportKey('OpenSSH')

    def update_ssh_keys(self):
        # this is ugly as it gets, but it's the easier way right now
        ssh_client = paramiko.SSHClient()
        ssh_client.load_system_host_keys('/etc/ssh/ssh_known_hosts')
        ssh_port = getattr(settings, 'OPENACCESS_ANALYSIS_SSH_PORT', 22)
        ssh_user = getattr(settings, 'OPENACCESS_ANALYSIS_SSH_USER', 'root')
        ssh_cmd = getattr(settings, 'OPENACCESS_ANALYSIS_SSH_CMD',
                          '/var/cmsopendata/update_ssh_keys.sh')
        updated_keys = '\n'.join([self.get_public_key(), self.extra_keys])
        cmd_line = '%s %s "%s"' % (ssh_cmd, self.username, updated_keys) 
        ssh_client.connect(settings.OPENACCESS_ANALYSIS_SSH_HOST,
                           port=ssh_port, username=ssh_user,
                           key_filename=settings.OPENACCESS_ANALYSIS_SSH_KEY)
        channel = ssh_client.get_transport().open_session()
        channel.exec_command(cmd_line)
        status = channel.recv_exit_status()        

    def _create_remote_user(self):
        # this should be as async as possible
        # ERROR CHECKING MISSING!!
        ssh_client = paramiko.SSHClient()
        ssh_client.load_system_host_keys('/etc/ssh/ssh_known_hosts')
        ssh_port = getattr(settings, 'OPENACCESS_ANALYSIS_SSH_PORT', 22)
        ssh_user = getattr(settings, 'OPENACCESS_ANALYSIS_SSH_USER', 'root')
        ssh_cmd = getattr(settings, 'OPENACCESS_ANALYSIS_SSH_CMD',
                          '/var/cmsopendata/createuser.sh')
        cmd_line = '%s %s "%s"' % (ssh_cmd, self.username, self.get_public_key())
        ssh_client.connect(settings.OPENACCESS_ANALYSIS_SSH_HOST,
                           port=ssh_port, username=ssh_user,
                           key_filename=settings.OPENACCESS_ANALYSIS_SSH_KEY)
        channel = ssh_client.get_transport().open_session()
        channel.exec_command(cmd_line)
        status = channel.recv_exit_status()

openaccess/forms.py
from django import forms

class SSHForm(forms.Form):
    ssh_key = forms.CharField(widget=forms.Textarea(attrs={'cols': 100,
                                                           'rows': 6}),
                              required=False, label="")

class OntologyForm(forms.Form):
    

cmsopendata/views.py
from django.views.generic.base import TemplateView

class IndexView(TemplateView):
    template_name = 'index.html'
    name = 'home'

openaccess/views.py
import json
import time
import hmac
from hashlib import sha1

from django.conf import settings
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'epl.settings')
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from openaccess.models import UserProfile
from openaccess.forms import SSHForm 

class IndexView(TemplateView):
    template_name = 'openaccess/index.html'


# Taken from django docs
class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


class AnalysisView(LoginRequiredMixin, TemplateView):
    template_name = 'openaccess/analysis.html'

    def get_context_data(self, **kwargs):
        context = super(AnalysisView, self).get_context_data(**kwargs)
        try:        
            profile = self.request.user.userprofile
        except UserProfile.DoesNotExist: 
            profile = UserProfile(user=self.request.user)
            profile.setup_user()
            profile.save() 
        secret = settings.OPENACCESS_GATEONE_SECRET
        auth_obj = {
            'api_key': settings.OPENACCESS_GATEONE_KEY,
            'upn': profile.username,
            'timestamp': str(int(time.time() * 1000)),
            'signature_method': 'HMAC-SHA1',
            'api_version': '1.0',
        }
        hash = hmac.new(secret, digestmod=sha1)
        hash.update(auth_obj['api_key'] + auth_obj['upn'] + auth_obj['timestamp'])
        auth_obj['signature'] = hash.hexdigest()
        context['gateone_auth_obj'] = json.dumps(auth_obj)
        context['gateone_connect_url'] = 'ssh://%s@%s' % (profile.username,
                                                          settings.OPENACCESS_ANALYSIS_SSH_HOST)
        context['gateone_url'] = settings.OPENACCESS_GATEONE_URL
        return context

class SSHView(LoginRequiredMixin, FormView):
    template_name = 'openaccess/ssh.html'
    form_class = SSHForm
    success_url = reverse_lazy('openaccess:ssh')

    def _get_user_profile(self):
        try:        
            profile = self.request.user.userprofile
        except UserProfile.DoesNotExist: 
            profile = UserProfile(user=self.request.user)
            profile.setup_user()
            profile.save() 
        return profile

    def get_initial(self):
        return {'ssh_key': self._get_user_profile().extra_keys}

    def get_context_data(self, **kwargs):
        context = super(SSHView, self).get_context_data(**kwargs)
        profile = self._get_user_profile()
        context['profile'] = profile
        return context

    def form_valid(self, form):
        profile = self._get_user_profile()
        profile.extra_keys = form.data['ssh_key']
        profile.save()
        profile.update_ssh_keys()
        return super(SSHView, self).form_valid(form)

class OntologyView(LoginRequiredMixin, FormView):
    template_name = 'openaccess/Ontology.html'
    form_class = OntologyForm

openaccess/templates/openaccess/analysis.html
{% extends "openaccess/base.html" %}

{% load staticfiles %}

{% block content %}


<section>
    <div class="container">
        <div class="gateone-container">
            <div id="gateone" />
        </div>
    </div>
</section>

{% endblock %}

{% block extra_js %}
<script src="{{ gateone_url }}/static/gateone.js"></script>
<script>

$( document ).ready(function() {
    authobj = {{ gateone_auth_obj | safe }};
    GateOne.init({url: "{{ gateone_url }}", 
                  embedded: false,
                  disableTermTransitions:true,
                  showTitle: true,
                  showToolbar: true,
                  fillContainer: true,
                  theme: "solarized",
                  autoConnectURL: "{{ gateone_connect_url | safe }}",
                  auth: authobj});
    GateOne.prefs.autoConnectURL = "{{ gateone_connect_url | safe }}";
}); 
</script>
{% endblock %}

openaccess/templates/openaccess/base.html
{% load staticfiles %}

{% url 'openaccess:home' as home_url %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CMS Open Data @ ifca.es</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/freelancer.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome-4.1.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"
                   href={% if request.get_full_path == home_url %}"#page-top"{% else %}{{ home_url }}{% endif %}>CMS Open Data @ ifca.es</a>
                    <img id="brand-badge" src="{% static 'img/beta_image.png' %}" alt="">
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
{% if user.is_authenticated %}
                    <li class="page-scroll">
                        <a href="{% url 'openaccess:analysis' %}">Start your analysis</a>
                    </li>
                    <li>
                        <a href="{% url 'openaccess:ssh' %}">SSH Access</a>
                    </li>
                    <li>
                        <a href="{% url 'account_logout' %}">Log out</a>
                    </li>
{% else %}
    {% if request.get_full_path == home_url %}
                    <li class="page-scroll">
                        <a href="#registration">Start your analysis</a>
                    </li>
    {% else %}
                    <li>
                        <a href="{{ home_url }}#registration">Start your analysis</a>

                    </li>
    {% endif %}
{% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="text-center">
         <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Built by</h3>
                        <p><a id="link-footer" href="http://aeonium.eu">Aeonium</a> and <a id="link-footer" href="http://www.ifca.unican.es">Instituto de Física de Cantabria (UC-CSIC)</a>.</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <p><img class="brand-logo-lg" src="{% static 'img/aeonium.png' %}" alt=""></p>
                        <p><img class="brand-logo-lg" src="{% static 'img/ifca.gif' %}" alt=""></p>
                        <p><img class="brand-logo-sm" src="{% static 'img/uc.png' %}" alt=""></p>
                        <p><img class="brand-logo-lg" src="{% static 'img/csic.jpg' %}" alt=""></p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>More Information</h3>
                        <p><a id="link-footer" href="http://press.web.cern.ch/press-releases/2014/11/cern-makes-public-first-data-lhc-experiments">CERN press release</a></p>
                        <p><a id="link-footer" href="http://cms.web.cern.ch/news/cms-releases-first-batch-high-level-lhc-open-data">CMS statement</a></p>
                        <p><a id="link-footer" href="http://www.i-cpan.es/detalleNoticia.php?id=401">Spanish press release</a></p>
                        <p><a id="link-footer" href="https://www.egi.eu/news-and-media/newsfeed/news_2014_041.html">EGI press release</a></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-inline">
                            <li>&copy; aeonium 2014</li>
                            <li><a href="{% url 'openaccess:termsofuse' %}" style="color:#fff">Terms of Use</a></li>
                            <li><a href="{% url 'openaccess:privacypolicy'%}" style="color:#fff">Privacy Policy</a></li>
                            <li><a href="{% url 'openaccess:contact' %}" style="color:#fff">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visble-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'js/classie.js' %}"></script>
    <!--<script src="js/cbpAnimatedHeader.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/freelancer.js' %}"></script>

    {% block extra_js %}{% endblock %}

    <!-- Contact Form JavaScript -->
<!--
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

-->
</body>

</html>

openaccess/templates/openaccess/contact.html
{% extends "openaccess/base.html" %}

{% load staticfiles %}

{% block content %}

<section class="infobar">
<div class="container">
  <h3>Contact</h3>
</div>
<div class="container">
     <div class="row">
          <div class="col-md-8">
               <div class="body">
                    <p> For troubleshooting, feature requests, and general help, contact with IFCA HelpDesk by sending an e-mail to grid.support@ifca.unican.es</p>
                    <p> Please make sure to include every possible detail about your problem (date, what were you trying to do, errors obtained, etc.)</p>
               </div>
          </div>
     </div>
</div>
</section>

{% endblock %}

openaccess/templates/openaccess/index.html
{% extends "openaccess/base.html" %}

{% load staticfiles %}

{% block content %}

<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="img-responsive bigimg" src="{% static 'img/lhc-detector-cms.jpg' %}" alt="">
    </div>
    <div class="col-md-6">
                <div class="intro-text">
                    <span class="name">About</span>
                    <hr class="star-light">
                    <span class="skills"><p>Look to the LHC CMS detector from inside, start analyzing its data.</p><p>Instituto de Física de Cantabria provides you with a virtual environment for CMS Open Data analysis for educational use, developed in collaboration with <a href="http://aeonium.eu">aeonium</a>. </p></span> 
                </div>
            </div>
        </div>
    </div>
</header>


<!-- Contact Section -->
<section id="registration">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Start your analysis</h2>
                <hr class="star-primary">
                <span><p>Learn about the CMS data at the <a href="http://opendata.cern.ch/">CERN OpenData Portal</a>. </p><p>In particular, if you are interested in performing real analysis, you can use this CMS OpenData Portal to perform them.</p><p>The environment is already setup to run an <a href="http://opendata.cern.ch/record/101">example code</a> for a simple analysis on Z decays to two leptons and the ZZ decays to four leptons.</p></span> 
                <span><p>This virtual environment is running using <a href="https://www.egi.eu/infrastructure/cloud/">EGI's Federated Cloud</a> infrastructure at IFCA.</p></span> 
            </div>
            <div class="col-md-4 col-md-offset-2 text-center"> 
                <a class="btn btn-success btn-lg" href="{% url 'account_signup' %}">Request an account &raquo;</a>
            </div>
            <div class="col-md-4 text-center"> 
                <a class="btn btn-success btn-lg" href="{% url 'account_login' %}">Login &raquo;</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

openaccess/templates/openaccess/privacypolicy.html
{% extends "openaccess/base.html" %}

{% load staticfiles %}

{% block content %}

<section class="infobar">
<div class="container">
  <h3>Privacy Policy</h3>
</div>
<div class="container">
     <div class="row">
          <div class="col-md-10">
               <div class="body">
                    <p>CMS OpenData Portal at ifca.es meets the CERN OpenData Portal <a href="http://http://opendata.cern.ch/privacy-policy">privacy policy</a>.<p>
                    {% comment %}<p>IFCA does not track, collect or retain personal information from users of CMS OpenData Portal, except as otherwise provided herein. In order to enhance CMS OpenData Portal at IFCA and monitor traffic, non-personal information such as IP addresses and cookies may be tracked and retained, as well as log files shared in aggregation with other community services. User provided information, like corrections of metadata or paper claims, will be integrated into the database without displaying its source and may shared with other services.</p>
                    <p>CMS OpenData Portal will take all reasonable measures to protect the privacy of its users and to resist service interruptions, intentional attacks, or other events that may compromise the security of the CMS OpenData Portal website.</p>{% endcomment %}
               </div>
          </div>
     </div>
</div>
</section>

{% endblock %}

openaccess/templates/openaccess/ssh.html
{% extends "openaccess/base.html" %}

{% load staticfiles %}

{% block content %}


<section>
    <div class="container">
        <h3>SSH access</h3>
        
        <div class="intro-text">
            <span class="skills"> <p>
            Login directly with ssh to the analsys environment by uploading a
            public ssh key in the form below.
            </p> </span>
            <span>
            <p>Then connect to cmsopendata.ifca.es as user {{ profile.username }}:</p></span>
            <div class="text-center"><p>ssh -i &lt;yourkey&gt; {{ profile.username }}@cmsopendata.ifca.es</p></div>
            </span>
        </div>
        <div>
            <h4>Public keys</h4>
            <p>Enter all the public keys you want the server to accept (one per line) and then save</p>
            <form action="" method="post">
            {% csrf_token %}
            <p class="small">
            {{ form }}
            </p>
            <input class="btn btn-success btn-lg" type="submit" value="Save" />
            </form>
        </div>
    </div>
</section>

{% endblock %}

{% block extra_js %}
<script src="{{ gateone_url }}/static/gateone.js"></script>
<script>

$( document ).ready(function() {
    authobj = {{ gateone_auth_obj | safe }};
    GateOne.init({url: "{{ gateone_url }}", 
                  embedded: false,
                  disableTermTransitions:true,
                  showTitle: true,
                  showToolbar: true,
                  fillContainer: true,
                  theme: "solarized",
                  autoConnectURL: "{{ gateone_connect_url | safe }}",
                  auth: authobj});
    GateOne.prefs.autoConnectURL = "{{ gateone_connect_url | safe }}";
}); 
</script>
{% endblock %}

openaccess/templates/openaccess/termsofuse.html
{% extends "openaccess/base.html" %}

{% load staticfiles %}

{% block content %}

<section class="infobar">
<div class="container">
  <h3>Terms of Use</h3>
</div>
<div class="container">
     <div class="row">
          <div class="col-md-10">
               <div class="body">
                    <p>CMS OpenData Portal at ifca.es meets the CERN OpenData Portal <a href="http://opendata.cern.ch/terms-of-use">terms of use</a>.<p>
               </div>
          </div>
     </div>
</div>
</section>

{% endblock %}